import marimo

__generated_with = "0.15.2"
app = marimo.App()


@app.cell
def _():
    import marimo as mo
    return (mo,)


@app.cell
def _():
    from pathlib import Path

    import altair as alt
    import polars as pl
    return Path, alt, pl


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    ## EDA with an interactive dashboard


    ### Bike sharing dataset

    As an example, we will explore the bike sharing dataset, taken from the [UCI Machine Learning Repository](http://archive.ics.uci.edu/ml/datasets/Bike+Sharing+Dataset)

    #### Data Set Information

    Bike sharing systems are new generation of traditional bike rentals where whole process from membership, rental and return back has become automatic. Through these systems, user is able to easily rent a bike from a particular position and return back at another position. Currently, there are about over 500 bike-sharing programs around the world which is composed of over 500 thousands bicycles. Today, there exists great interest in these systems due to their important role in traffic, environmental and health issues.

    Apart from interesting real world applications of bike sharing systems, the characteristics of data being generated by these systems make them attractive for the research. Opposed to other transport services such as bus or subway, the duration of travel, departure and arrival position is explicitly recorded in these systems. This feature turns bike sharing system into a virtual sensor network that can be used for sensing mobility in the city. Hence, it is expected that most of important events in the city could be detected via monitoring these data.

    #### Attribute Information

    Both hour.csv and day.csv have the following fields, except hr which is not available in day.csv

    - instant: record index
    - dteday : date
    - season : season (1:winter, 2:spring, 3:summer, 4:fall)
    - yr : year (0: 2011, 1:2012)
    - mnth : month ( 1 to 12)
    - hr : hour (0 to 23)
    - holiday : weather day is holiday or not (extracted from [Web Link])
    - weekday : day of the week
    - workingday : if day is neither weekend nor holiday is 1, otherwise is 0.
    + weathersit :
      - 1: Clear, Few clouds, Partly cloudy, Partly cloudy
      - 2: Mist + Cloudy, Mist + Broken clouds, Mist + Few clouds, Mist
      - 3: Light Snow, Light Rain + Thunderstorm + Scattered clouds, Light Rain + Scattered clouds
      - 4: Heavy Rain + Ice Pallets + Thunderstorm + Mist, Snow + Fog
    - temp : Normalized temperature in Celsius. The values are derived via (t-t_min)/(t_max-t_min), t_min=-8, t_max=+39 (only in hourly scale)
    - atemp: Normalized feeling temperature in Celsius. The values are derived via (t-t_min)/(t_max-t_min), t_min=-16, t_max=+50 (only in hourly scale)
    - hum: Normalized humidity. The values are divided to 100 (max)
    - windspeed: Normalized wind speed. The values are divided to 67 (max)
    - casual: count of casual users
    - registered: count of registered users
    - cnt: count of total rental bikes including both casual and registered
    """
    )
    return


@app.cell
def _(Path):
    HERE = Path(__file__).parent
    return (HERE,)


@app.cell
def _(HERE, pl):
    hourly = (
        pl.read_csv(HERE / "data/bike-sharing/hour.csv")
        .with_columns(time=pl.time(pl.col("hr"), 0, 0))
        .with_columns(datetime=pl.col("dteday").str.to_date("%Y-%m-%d").dt.combine(pl.col("time")))
    )

    daily = pl.read_csv(HERE / "data/bike-sharing/bike-sharing-daily-processed.csv").with_columns(
        pl.col("dteday").str.to_date("%Y-%m-%d")
    )
    return (daily,)


@app.cell
def _(alt, daily):
    brush = alt.selection(type="interval", encodings=["x"])

    base = alt.Chart(daily).mark_line().encode(x="dteday", y="cnt").properties(width=800, height=200)

    overview = base.properties(height=50).add_selection(brush)
    detail = base.encode(alt.X("dteday:T", scale=alt.Scale(domain=brush)))
    return detail, overview


@app.cell
def _(detail, overview):
    detail & overview
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    ## Aggregations in Altair

    Use the `TimeUnit` transformations in Altair to do `group_by`s.
    """
    )
    return


@app.cell
def _(alt, daily):
    alt.Chart(daily).mark_line().encode(x="yearmonth(dteday):T", y="sum(cnt):Q")
    return


@app.cell
def _():
    return


if __name__ == "__main__":
    app.run()
